DATA:
  PATH_TO_DATA_DIR: ~/REMAG  
  NUM_FRAMES: 64
  SAMPLING_RATE: 2
  DECODING_BACKEND: torchvision  # Not used but safe to keep
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  INV_UNIFORM_SAMPLE: False
  RANDOM_FLIP: True
  MEAN: [123.675, 116.28, 103.53]  # Assuming [0, 255] RGB frames
  STD: [58.395, 57.12, 57.375]
  TEST_CLASS_IDS: [5, 6, 8]

TRAIN:
  ENABLE: True
  DATASET: "REMAGDataset"
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True

TEST:
  ENABLE: True
  DATASET: "REMAGDataset"
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1  # Increase for final eval if needed

MODEL:
  NUM_CLASSES: 10  # <<< UPDATE to match your dataset
  ARCH: slow
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5

MVIT:
  ZERO_DECAY_POS_CLS: False
  CLS_EMBED_ON: False # MUST STAY FALSE FOR REVMVIT
  SEP_POS_EMBED: True
  USE_ABS_POS: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: False
  DROPPATH_RATE: 0.05
  NORM: "layernorm"
  MODE: "conv"
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]

  REV:
    ENABLE: True
    RESPATH_FUSE: "concat"
    BUFFER_LAYERS: [1, 3, 14]
    RES_PATH: "conv"

AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 2
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False

MIXUP:
  ENABLE: True
  ALPHA: 0.8
  LABEL_SMOOTH_VALUE: 0.1
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5

SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 200
  WARMUP_EPOCHS: 50.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 7e-2
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR: 0.000001
  OPTIMIZING_METHOD: adamw

DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./outputs/remag
