DATA:
  PATH_TO_DATA_DIR_SYN: "/home/emilykim/Desktop/HAR-project/REMAG_syn/"
  PATH_TO_DATA_DIR: "/home/emilykim/Desktop/HAR-project/REMAG_new"
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  DECODING_BACKEND: torchvision 
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  INV_UNIFORM_SAMPLE: False
  RANDOM_FLIP: True
  MEAN: [123.675, 116.28, 103.53]  
  STD: [58.395, 57.12, 57.375]
  TEST_CLASS_IDS: [5, 6, 8]
  TRAIN_IDS: [1, 3, 10, 15, 19] #, 22, 2, 7, 11, 13
  TEST_IDS: [5, 6, 8, 21, 20]
  SYN_GEN: True


TRAIN:
  ENABLE: True
  DATASET: "REMAGDataset"
  BATCH_SIZE: 24
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: "pretrained/MViTv2_S_16x4_k400_f302660347.pyth"
  CHECKPOINT_FILE_PATH: "outputs/remag-15-viewA-syn-mvit-woBrightness-shorter/checkpoints/checkpoint_epoch_00018.pyth"
  CHECKPOINT_EPOCH_RESET: True

TEST:
  ENABLE: False
  DATASET: "REMAGDataset"
  BATCH_SIZE: 48
  CHECKPOINT_FILE_PATH: "outputs/remag-10/checkpoints/checkpoint_epoch_00056.pyth" #"pretrained/MViTv2_S_16x4_k400_f302660347.pyth"
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1  # Increase for final eval if needed
  SAVE_RESULTS_PATH: "results"

MODEL:
  NUM_CLASSES: 16
  ARCH: slow
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5

MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True

AUG:
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 2
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False

MIXUP:
  ENABLE: False
  ALPHA: 0.8
  LABEL_SMOOTH_VALUE: 0.1
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5

SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.001
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 3 #
  WARMUP_EPOCHS: 50.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 7e-2
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: adamw

TENSORBOARD:
  ENABLE: True      
  CATEGORIES_PATH: "actions.json"
  CONFUSION_MATRIX: 
    ENABLE: True

DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True

NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./outputs/remag-15-viewA-syn-mvit-woBrightness-shorter
LOG_PERIOD: 5
